import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import {Montserrat} from "next/font/google";
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'
import 'bootstrap-icons/font/bootstrap-icons.css';
import Nav from "@/components/smallScreenNav/Nav";



const montserrat = Montserrat({subsets:["latin"], weight:["400","500","600","700"]});

export const metadata: Metadata = {
  title: "Bandage",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={montserrat.className}>
      <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
