export const productsData = [
    {
  id:"1",    
  image: "/Images/products/product1.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"2",    
  image: "/Images/products/product2.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
  description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  availabilty: "In stock",
  price: "1433.9$",
  circles:true
    },
    {
  id:"3",    
  image: "/Images/products/product3.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  availabilty: "In stock",
  price: "1433.9$",
  circles:true
    },
     {
   id:"4",   
  image: "/Images/products/product4.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"5",    
  image: "/Images/products/product5.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"6",    
  image: "/Images/products/product6.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
  description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"7",    
  image: "/Images/products/product7.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
  description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"8",    
  image: "/Images/products/product8.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
  description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"9",    
  image: "/Images/products/product9.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"10",    
  image: "/Images/products/product10.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"11",    
  image: "/Images/products/product11.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"12",    
  image: "/Images/products/product12.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id: "13",    
  image: "/Images/products/product13.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    } ,
     {
  id:"14",    
  image: "/Images/products/product14.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"15",    
  image: "/Images/products/product15.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
     {
  id:"16",    
  image: "/Images/products/product16.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
    
      {
  id:"17",    
  image: "/Images/products/product17.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"18",    
  image: "/Images/products/product18.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"19",    
  image: "/Images/products/product19.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"20",    
  image: "/Images/products/product20.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"21",    
  image: "/Images/products/product21.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"22",    
  image: "/Images/products/product22.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"23",    
  image: "/Images/products/product23.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    },
      {
  id:"24",    
  image: "/Images/products/product24.jpeg",
  heading: "English Department",
  subHeading: "Graphic Design",
   description: "Met minim Mollie non desert Alamo est sit cliquey dolor do met sent. RELIT official consequent door ENIM RELIT Mollie. Excitation venial consequent sent nostrum met. ",
  oldPrice: "10$",
  newPrice:"20$",
  price: "1433.9$",
  availabilty: "In stock",
  circles:true
    }
] 


